### ISSUE TITLE
TN: Make all tinman error messages go to stdout

### ISSUE THREAD

**Issue by relativityboy** [steemit/steem-deployments#15]
As a @jredbeard I want to be able to see error messages in our error logging platorm so that I don't have to spend extra time and mental effort looking in a separate place to view them.

**AC**
- [ ] timan submit error messages go to stdout
- [ ] gatling error messages go to stdout

**Comment by jredbeard** [comment]
Additional reason: we wouldn't want containers local storage filling up with fail logs

**Comment by relativityboy** [comment]
Closing per above.
