### ISSUE TITLE
TN: Steem-Deployments: Add parameter support 

### ISSUE THREAD

**Issue by relativityboy** [steemit/steem-deployments#32]
Steem Deployments Component: As a dev, there are times I may not want to run gatling, or some other stage of the testnet process, or pass parameters, _so that I can have a testnet that exactly suits my needs, or the needs of the community_.

**AC**
- [x] document the list of stages and their parameters in a comment `# Results`
- [ ] testnet script supports them.

**Comment by inertia186** [comment]
# Result

The deploy is intended to proceed normally unless the following environment variables are set:

* `SKIP_BACKFILL_ACTIONS` - uses actions that contains no backfill
* `SKIP_SEED_NODE` - disables the public facing seed node and disables init-_n_ witnesses
* `SKIP_DASHBOARD` -  disables `tinman server`
* `SKIP_GATLING` - disables `tinman gatling` in the final loop

Example:

```bash
SKIP_BACKFILL_ACTIONS="YES" SKIP_GATLING="YES" testnetinit.sh
```

**Comment by relativityboy** [comment]
SKIP_ACCOUNT_CREATION could be another one. boot it, write some empty blocks to bring us up to present, create & vote in the witnesses. Ur done. Super fast TN startup.
