### ISSUE TITLE
TN: Use tinman warden to trigger gatling

### ISSUE THREAD

**Issue by relativityboy** [steemit/steem-deployments#9]
As a shell script, I want to utilize warden to trigger gatling when launching a testnet so that I don't have to have so much domain specific knowledge, and so that I don't have to be updated as much.

**AC**
- [ ] [testnetinit.sh](https://github.com/steemit/steem-deployments/blob/master/dev/testnet/testnetinit.sh) outsources `tinman/gatling` launch logic to `tinman/warden` [PR for warden](https://github.com/steemit/tinman/issues/93)

**Comment by inertia186** [comment]
Possible implementation is to replace this:

https://github.com/steemit/steem-deployments/blob/master/dev/testnet/testnetinit.sh#L111-L125

... with something like:

```bash
while [[ $all_clear -ne 0 ]]
do
    tinman warden -s http://localhost:8091
    all_clear=$?
    echo Waiting for warden to sound the all-clear.
    sleep 60
done
```
